version: "3.7"

services:
    private-note:
        build: .
        environment:
            FLASK_APP: app.py
        ports:
            - "8080:8080"
        container_name: private-note

    database:
        image: mysql
        volumes:
            - database-volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret

volumes:
    database-volume:
        external: true